import { Link } from 'react-router-dom'
import Layout from '../components/layout/Layout'

const EFFECTIVE_DATE = 'March 15, 2025'
const EMAIL = 'shortlistr@gmail.com'

function Section({ id, title, children }) {
  return (
    <section id={id} className="mb-10">
      <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">{title}</h2>
      <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed space-y-3">
        {children}
      </div>
    </section>
  )
}

export default function DisclaimerPage() {
  return (
    <Layout>
      <div className="bg-white dark:bg-navy-900 min-h-screen">
        <div className="max-w-3xl mx-auto px-6 py-16">

          <div className="mb-12">
            <h1 className="text-4xl font-bold text-slate-900 dark:text-white mb-3">Legal Disclaimer</h1>
            <p className="text-slate-500 dark:text-slate-400 text-sm">Effective date: {EFFECTIVE_DATE}</p>
          </div>

          <div className="mb-10 bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/30 rounded-xl p-5">
            <p className="text-amber-800 dark:text-amber-400 text-sm leading-relaxed font-medium">
              ShortListr is a writing assistance tool powered by AI. AI outputs can be wrong. You are responsible for reviewing everything the Service generates before using it in a job application. By using the Service, you accept the limitations described on this page.
            </p>
          </div>

          <div className="bg-slate-50 dark:bg-navy-800 border border-slate-200 dark:border-white/10 rounded-xl p-5 mb-10 text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
            <p>
              This page defines the boundaries of what ShortListr is responsible for. It is part of the agreement you enter when you use the Service, alongside our{' '}
              <Link to="/terms" className="text-electric-600 dark:text-electric-400 hover:underline">Terms of Service</Link>{' '}
              and <Link to="/privacy" className="text-electric-600 dark:text-electric-400 hover:underline">Privacy Policy</Link>.
              The full liability terms — including caps and class action waiver — are in the{' '}
              <Link to="/terms" className="text-electric-600 dark:text-electric-400 hover:underline">Terms of Service</Link>.
            </p>
          </div>

          <Section id="no-professional-advice" title="1. Not Professional Advice">
            <p>
              ShortListr is a software writing tool. Nothing it generates — resume rewrites, bullet point suggestions, cover letters, or AI chat responses — constitutes career advice, legal advice, HR consulting, or professional employment guidance of any kind.
            </p>
            <p>
              The Service is designed to help you write better. It is not a substitute for the judgment of a career coach, recruiter, attorney, or any other qualified professional. If you need professional guidance, consult one.
            </p>
          </Section>

          <Section id="ai-accuracy" title="2. AI Outputs May Be Wrong">
            <p>
              The AI systems that power ShortListr — like all large language models — can and do produce incorrect, outdated, or fabricated information. Known failure modes include:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2">
              <li>Generating job titles, dates, skills, or accomplishments that don't match your actual background</li>
              <li>Misreading the intent of a job description</li>
              <li>Producing phrasing that doesn't align with current hiring norms</li>
              <li>Inconsistent quality depending on how inputs are phrased</li>
            </ul>
            <p>
              <strong className="text-slate-800 dark:text-slate-200">ShortListr makes no warranty — express or implied — about the accuracy, completeness, or fitness of any AI-generated output for any purpose.</strong>
            </p>
          </Section>

          <Section id="user-responsibility" title="3. You Are Responsible for What You Submit">
            <p>
              Before you use any content generated by ShortListr in a job application or professional context, you must verify that:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2">
              <li>Every fact, date, employer name, job title, and skill is accurate</li>
              <li>Nothing has been added or exaggerated that doesn't reflect your real background</li>
              <li>The content honestly represents who you are and what you've done</li>
              <li>The tone and framing are appropriate for the role you're applying to</li>
            </ul>
            <p>
              Submitting false or misleading information to a prospective employer — regardless of how it was generated — is entirely your responsibility. ShortListr bears no liability for the professional, legal, or reputational consequences of content you submit to others.
            </p>
          </Section>

          <Section id="ai-detection" title="4. No Guarantee of Passing AI Detection Tools">
            <p>
              ShortListr uses AI to rewrite and optimize resume content. We do not guarantee, claim, or imply that content generated by the Service will pass AI-detection tools, AI-writing checkers, or any automated screening software used by employers.
            </p>
            <p>
              AI writing detection tools are unreliable, vary widely in methodology, and frequently produce false positives — flagging human-written content as AI-generated. ShortListr has no control over which detection tools employers use or how they interpret results.
            </p>
            <p>
              <strong className="text-slate-800 dark:text-slate-200">All resume content generated by ShortListr is AI-assisted. You are responsible for reviewing it, editing it to reflect your own voice, and deciding whether and how to use it.</strong>
            </p>
          </Section>

          <Section id="no-employment-guarantee" title="5. No Employment Outcomes Guaranteed">
            <p>
              Using ShortListr does not guarantee job interviews, employment offers, salary increases, or any other outcome. Hiring decisions are made by employers based on factors that are entirely outside our control.
            </p>
            <p>
              Any performance statistics referenced in ShortListr marketing materials — such as improved callback rates — are general industry estimates, not guarantees of individual results. Do not rely on them as promises.
            </p>
          </Section>

          <Section id="liability" title="6. Scope of Liability">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, SHORTLISTR IS NOT LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE OR RELIANCE ON AI-GENERATED CONTENT — INCLUDING BUT NOT LIMITED TO:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2">
              <li>Errors or inaccuracies in AI outputs</li>
              <li>Failure to obtain any job or career outcome</li>
              <li>Actions taken by employers based on materials you submitted</li>
              <li>Loss of data, resume content, or version history</li>
              <li>Service interruptions or technical failures</li>
            </ul>
            <p>
              THIS LIMITATION APPLIES REGARDLESS OF THE LEGAL THEORY UNDER WHICH A CLAIM IS BROUGHT. For the full liability cap and class action waiver, see our{' '}
              <Link to="/terms" className="text-electric-600 dark:text-electric-400 hover:underline">Terms of Service</Link>.
            </p>
          </Section>

          <Section id="use-at-own-risk" title="7. Use at Your Own Risk">
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND — EXPRESS OR IMPLIED — INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. YOU ASSUME FULL RESPONSIBILITY FOR HOW YOU USE THE SERVICE AND ITS OUTPUTS.
            </p>
          </Section>

          <Section id="external-links" title="8. External Content">
            <p>
              The Service may link to third-party websites or allow you to fetch content from external job postings. We have no control over external content, do not endorse it, and are not responsible for any harm resulting from your use of it.
            </p>
            <p>
              When you use the job description URL fetching feature, you are responsible for confirming that the content retrieved accurately represents the role you're applying for.
            </p>
          </Section>

          <Section id="contact" title="Questions">
            <p>Questions about this disclaimer? Contact us:</p>
            <div className="mt-3 bg-slate-50 dark:bg-navy-800 border border-slate-200 dark:border-white/10 rounded-xl p-5">
              <p className="font-semibold text-slate-800 dark:text-slate-200 mb-1">ShortListr</p>
              <p><a href={`mailto:${EMAIL}`} className="text-electric-600 dark:text-electric-400 hover:underline">{EMAIL}</a></p>
            </div>
          </Section>

        </div>
      </div>
    </Layout>
  )
}
